services:
  # --- LA VÍCTIMA (OWASP Juice Shop) ---
  victim-juice:
    image: bkimminich/juice-shop
    container_name: lab_victim
    restart: always
    security_opt:
      - no-new-privileges:true 
    ports:
      - "3000:3000"
    networks:
      - hacking-net
      
    # --- CAMBIO: VOLUMEN NOMBRADO ---
    # Usamos un volumen gestionado por Docker para no borrar archivos internos
    volumes:
      - juice_shop_data:/juice-shop/data
    
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M

  # --- EL ATACANTE (Kali Linux) ---
  attacker-kali:
    image: kalilinux/kali-rolling
    container_name: lab_attacker
    tty: true
    command: /bin/bash
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - hacking-net
    volumes:
      - ./mis-reportes:/root/reportes:rw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

networks:
  hacking-net:
    driver: bridge

# --- NUEVO BLOQUE AL FINAL ---
volumes:
  juice_shop_data:
